### PR TITLE
fixed: Bundle lookup

### PR DESCRIPTION
**Pull request by projectvim**

### CODE REVIEW

**Comment by tikhop** [comment]
@projectvim Thank you for your contribution. Personally, I don't think it will work properly when using SwiftPM. The Apple root certificate can't be included when using SwiftPM and you have to add it manually into the main Bundle. I can use your code in order to check the library's bundle first and then keep the current code in case if the certificate hasn't been found.

**Comment by projectvim** [comment]
Oh, I didn't check it with SwiftPM, but current version doesn't work even with cocoapods,  if`TPInAppReceipt` is statically linked inside some framework (not build with `use_frameworks!` )

**Comment by tikhop** [comment]
@projectvim I see, I haven't tested in that way. I will integrate your changes later today. Thanks again for your contribution.

**Comment by tikhop** [comment]
@projectvim Just updated cocoapods and master branch.

**Pull request closed without merging**
