### PR TITLE
Added Chain of trust verification and signature verification using iTunes Store Cert in the app receipt

### PR DESCRIPTION
**Pull request by cupnoodle**
Added X509 parser and signature verification using iTunes Store Cert in the app receipt

### CODE REVIEW

**Comment by tikhop** [comment]
@cupnoodle Thanks for your work. I will review it and merge if everything is fine. Thanks again.

**Comment by cupnoodle** [comment]
@tikhop Welcome, just added chain of trust verification as well, hope this helps

Thanks for this library! I have been using it in my apps after discovering this library, hope I can help with these contribution.

**Comment by tikhop** [comment]
@cupnoodle Cool, thanks again. I'm glad you find it useful.

**Comment by tikhop** [comment]
@cupnoodle btw, have you got a chance to check whether it works fine with OSX and watches. 
Thanks, P

**Comment by cupnoodle** [comment]
@tikhop  Just tested with Mac App Store app receipt (using the receipt from Xcode downloaded from MAS), the `verifySignature() functions` works!

```
func verifySignature() throws
    {
        try checkSignatureExistance()
        try checkAppleRootCertExistence()
        try checkChainOfTrust()
        try checkSignatureValidity()
    }
```

Unfortunately I don't have AppleWatch though, but the receipt format should be the same

**Comment by tikhop** [comment]
@cupnoodle Yeah, if you just take a receipt from any platform it works. Have you tried to change a building target from ios to other platforms? I haven't checked yet, but I, as I remember, osx and ios have a different API for security stuff, I might be wrong tho.

Thanks,
P

**Comment by cupnoodle** [comment]
Got it, I just tried building and archiving the library for iOS, macOS and tvOS. They work fine but need to bump iOS version to 10.0, macOS version to 10.12 and tvOS version to 10.0 as the SecKeyCreateWithData and other security related API need these minimum version : https://developer.apple.com/documentation/security/1643701-seckeycreatewithdata

For Key/Cert/Signature related API, iOS / macOS share the same security framework by Apple : https://developer.apple.com/documentation/security

For watchOS it failed to archive because starting from watchOS 2 , UIDevice is absent from watchOS : 
Screenshot 2019-11-19 at 11 34 00 PM

**Comment by tikhop** [comment]
Thank you, I will fix watchOS, my bad. Regarding OSX, I think it's better to keep the same version and wrap some code with `@available(macOS 10.12, *)`

**Comment by cupnoodle** [comment]
> Thank you, I will fix watchOS, my bad. 
Welcome, no worries, I think receipt validation code should run on the companion iOS app for the watchOS app on most cases.

>Regarding OSX, I think it's better to keep the same version and wrap some code with `@available(macOS 10.12, *)`
Hmm, this means that the signature verification stuff won't work for macOS 10.11 and earlier, is this fine?

**Comment by tikhop** [comment]
> Hmm, this means that the signature verification stuff won't work for macOS 10.11 and earlier, is this fine?

yeah, only that part won't work, so for those who still developing for an older systems it's fine.

**Comment by cupnoodle** [comment]
Got it, I have added `if #available(OSX 10.12, iOS 10.0, tvOS 10.0, watchOS 3.0, *)` block on functions that requires higher OS version.

**Comment by tikhop** [comment]
@cupnoodle Merged, I will update cocoapods shortly

**Comment by tikhop** [comment]
@cupnoodle just updated cocoapod 

Thanks again for your help.
P

**Pull request merged**
